[tool.poetry]
name = "gsplat-pip"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = {version = "^2.3.1+cu121", source = "torch_cu121"}
torchvision = {version = "^0.18.1+cu121", source = "torch_cu121"}
torchaudio = {version = "^2.3.1+cu121", source = "torch_cu121"}
pycolmap = {git = "https://github.com/rmbrualla/pycolmap", rev = "cc7ea4b7301720ac29287dbe450952511b32125e"}
viser = "^0.2.1"
nerfview = "0.0.2"
imageio = {extras = ["ffmpeg"], version = "^2.34.2"}
numpy = "1.26.4"
scikit-learn = "^1.5.0"
tqdm = "^4.66.4"
torchmetrics = {extras = ["image"], version = "^1.4.0.post0"}
opencv-python = "^4.10.0.84"
tyro = "^0.8.5"
pillow = "^10.3.0"
tensorboard = "^2.17.0"
gsplat = "^1.0.0"


[[tool.poetry.source]]
name = "torch_cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
